version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: hybridshop-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${PORT_POSTGRES}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongo:
    image: mongo:latest
    container_name: hybridshop-mongo
    ports:
      - "${PORT_MONGO}:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:alpine
    container_name: hybridshop-redis
    ports:
      - "${PORT_REDIS}:6379"
  
  minio:
    image: minio/minio
    container_name: hybridshop-minio
    ports:
      - "${PORT_MINIO_API:-9000}:9000"
      - "${PORT_MINIO_CONSOLE:-9001}:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    restart: always

  minio-init:
    image: minio/mc
    container_name: hybridshop-minio-init
    depends_on:
      - minio
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_BUCKET_NAME: ${MINIO_BUCKET_NAME}
    entrypoint: >
      sh -c "
      until mc alias set myminio http://minio:9000 $$MINIO_ROOT_USER $$MINIO_ROOT_PASSWORD; do echo 'Czekam na MinIO...'; sleep 1; done;
      mc mb myminio/$$MINIO_BUCKET_NAME --ignore-existing;
      mc anonymous set download myminio/$$MINIO_BUCKET_NAME;
      exit 0;
      "

  rabbitmq:
    image: rabbitmq:3-management
    container_name: hybridshop-rabbitmq
    ports:
      - "${PORT_RABBITMQ_AMQP}:5672"
      - "${PORT_RABBITMQ_MGMT}:15672"

  mailpit:
    image: axllent/mailpit:latest
    container_name: hybridshop-mailpit
    ports:
      - "1025:1025" 
      - "8025:8025" 

  api-gateway:
    image: hybridshop-gateway
    container_name: hybridshop-gateway
    build:
      context: .
      dockerfile: src/ApiGateway/Dockerfile
    ports:
      - "${PORT_API_GATEWAY}:8080"
    depends_on:
      - auth-service
      - product-service
      - order-service
      - notification-service

  auth-service:
    image: hybridshop-auth
    container_name: hybridshop-auth
    build:
      context: .
      dockerfile: src/Services.Auth/Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=${DB_CONNECTION_STRING}
      - EventBus__HostName=rabbitmq
      - Jwt__Key=${JWT_KEY}
      - Jwt__Issuer=${JWT_ISSUER}
      - Jwt__Audience=${JWT_AUDIENCE}
    depends_on:
      - postgres
      - rabbitmq

  product-service:
    image: hybridshop-product
    container_name: hybridshop-product
    build:
      context: .
      dockerfile: src/Services.Product/Dockerfile
    environment:
      - MongoSettings__ConnectionString=${MONGO_CONNECTION_STRING}
      - MongoSettings__DatabaseName=HybridShop_Product
      - ConnectionStrings__Redis=${REDIS_CONNECTION_STRING}
      - Jwt__Key=${JWT_KEY}
      - Jwt__Issuer=${JWT_ISSUER}
      - Jwt__Audience=${JWT_AUDIENCE}
      - InternalServices__AuthGrpcUrl=${InternalServices__AuthGrpcUrl}
      - Minio__Endpoint=minio:9000
      - Minio__AccessKey=${MINIO_ROOT_USER}
      - Minio__SecretKey=${MINIO_ROOT_PASSWORD}
      - Minio__BucketName=${MINIO_BUCKET_NAME}
    depends_on:
      - mongo
      - redis
      - auth-service
      - minio

  order-service:
    image: hybridshop-order
    container_name: hybridshop-order
    build:
      context: .
      dockerfile: src/Services.Order/Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=${DB_CONNECTION_STRING}
      - ConnectionStrings__Redis=${REDIS_CONNECTION_STRING}
      - EventBus__HostName=rabbitmq
      - Jwt__Key=${JWT_KEY}
      - Jwt__Issuer=${JWT_ISSUER}
      - Jwt__Audience=${JWT_AUDIENCE}
      - InternalServices__ProductGrpcUrl=${InternalServices__ProductGrpcUrl}
      - InternalServices__AuthGrpcUrl=${InternalServices__AuthGrpcUrl}
    depends_on:
      - postgres
      - redis
      - rabbitmq
      - auth-service

  notification-service:
    image: hybridshop-notification
    container_name: hybridshop-notification
    build:
      context: .
      dockerfile: src/Services.Notification/Dockerfile
    environment:
      - EventBus__HostName=rabbitmq
      - Jwt__Key=${JWT_KEY}
      - Jwt__Issuer=${JWT_ISSUER}
      - Jwt__Audience=${JWT_AUDIENCE}
      - InternalServices__AuthGrpcUrl=${InternalServices__AuthGrpcUrl}
      - Smtp__Host=mailpit
      - Smtp__Port=1025
      - Smtp__From=noreply@hybridshop.com
    depends_on:
      - rabbitmq
      - auth-service
      - mailpit

volumes:
  postgres_data:
  mongo_data:
  minio_data: